reviews:
  request_changes_workflow: true
  high_level_summary: true
  poem: false
  review_status: true
  auto_review:
    enabled: true
    drafts: false
  path_filters:
    - "!build/**"
    - "!_deps/**"

chat:
  auto_reply: true
